# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" , "release/*"]
  pull_request:
    branches: [ "main" , "develop" , "release/*"]


jobs:
  build:

    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Antoshchenko Roman"  
      GROUP: "M3111"

    steps:
    - name: Output user information
      run: |
        echo "$FULL_NAME"
        echo "$GROUP"
        echo "$GITHUB_ACTOR"
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Run tests
      run: |
        python -m unittest discover -s tests -p "test_*.py"


    - name: Lint code with flake8
      run: |
        pip install flake8
          flake8 .
