# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Python application

on:
  push:
    branches: [ "main" , "release/*"]
  pull_request:
    branches: [ "main" , "develop" , "release/*"]


jobs:
  build:

    runs-on: ubuntu-latest

    env:
      FULL_NAME: "Antoshchenko Roman"  
      GROUP: "M3111"


    steps:
    - name: Output user information
      run: |
        echo "$FULL_NAME"
        echo "$GROUP"
        echo "$GITHUB_ACTOR"
 
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: "3.13"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: Lint with flake8
      run: |
        # stop the build if there are Python syntax errors or undefined names
        flake8 . --count --select=E9,F63,F7,F82 --show-source --statistics
        # exit-zero treats all errors as warnings. The GitHub editor is 127 chars wide
        flake8 . --count --exit-zero --max-complexity=10 --max-line-length=127 --statistics
    - name: Test with pytest
      run: |
        pytest
